<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>predictive risk</name>
  <uuid>160dccb5-52f9-4672-bffd-d50b1ba0dc03</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Scoreboard where 
	the Confidence is 0.87634 , 
	the Segment is "Finance" , 
	High risk is false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
